stages:
  - debug
  - build
  - test

check-docker-permissions:
  stage: debug
  tags:
    - docker
  script:
    - whoami
    - groups
    - ls -l /var/run/docker.sock
    - docker info || echo "Docker not accessible"


build-image:
  stage: build
  tags:
    - docker
  script:
    - docker build -t dq-discovery .


run-image:
  stage: test
  tags:
    - docker
  script:
    - docker run --rm dq-discovery echo "Container ran successfully!"
