stages:
  - build
  - deploy


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_REGISTRY: registry.gitlab.com/cyclops4100006/dqrulediscovery

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"


build-image:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_REGISTRY .
    - docker push $IMAGE_REGISTRY

run-image:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Deploying DQRuleDiscovery..."
    - docker pull $IMAGE_REGISTRY
    - docker stop dqrulediscovery || true
    - docker rm dqrulediscovery || true
    - docker run -d --name dqrulediscovery --network ontopicsuite_application -p 5000:5000 -e METADATA_MANAGER_ENDPOINT=metadata-manager:8080 -e MINIO_ENDPOINT=minio:9000 -e MINIO_ACCESS_KEY=minioadmin -e MINIO_SECRET_KEY=minioadmin123 $IMAGE_REGISTRY
    #- docker network connect long-term-storage_default dqrulediscovery
    - docker ps

