stages:
  - build
  - test

build-image:
  stage: build
  tags:
    - dockergood
  script:
    - docker build -t dq-discovery .


run-image:
  stage: test
  tags:
    - dockergood
  script:
    - docker run --rm dq-discovery echo "Container ran successfully!"
